on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [18, 20]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      ## web build
      - run: yarn --cwd ./wj-markdown-editor-web
      - run: yarn --cwd ./wj-markdown-editor-web build
      ## electron make
      - run: yarn --cwd ./wj-markdown-editor-electron
      - run: yarn --cwd ./wj-markdown-editor-electron run make
      ## zip file
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wj-markdown-editor
          path: ./wj-markdown-editor-electron/electron-build/win-unpacked
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
