on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: pwd
      - name: web build
      - run: yarn --cwd ./wj-markdown-editor-web
      - run: yarn --cwd ./wj-markdown-editor-web build
      - name: electron make
      - run: yarn --cwd ./wj-markdown-editor-electron
      - run: yarn --cwd ./wj-markdown-editor-electron run make
      - name: print log
      - run: ls
      - run: ls ./wj-markdown-editor-electron
      - run: ls ./wj-markdown-editor-electron/electron-build
      # - name: zip files
      #   run: zip -r wj-markdown-editor.zip ./dist
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: zip-file
      #     path: wj-markdown-editor.zip
      #     retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
